default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: tertecno_development

test:
  <<: *default
  database: tertecno_test

production:
  <<: *default
  database: tertecno_development
  username: tertecno
  password: <%= ENV['TERTECNO_DATABASE_PASSWORD'] %>
